# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.TextField(default='Practice')),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Less important'), (2, 'Moderate Important'), (3, 'Very Important')])),
                ('revise_count', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_solved', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Category')),
            ],
            options={
                'ordering': ['priority', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('referred_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ManyToManyField(to='todo.Question')),
            ],
            options={
                'ordering': ['-referred_count'],
            },
        ),
    ]
